In [53]:
''' 
 Author: Yoonhyuck WOO / JBNU_Industrial Information system Engineering
 Date; 7. 20. 2021 - 7. 21. 2021
 Title: Linear Regression
 Reference: https://wikidocs.net/53545'''

' \n Author: Yoonhyuck WOO / JBNU_Industrial Information system Engineering\n Date; 7. 20. 2021 - 7. 21. 2021\n Title: Linear Regression\n Reference: https://wikidocs.net/53545'

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x_train = torch.FloatTensor([[1,2,3],[2,2,3],[3,2,3],[4,2,3],[5,2,3],[6,2,3],[7,2,3],[8,2,3],[9,2,3]])
y_train = torch.FloatTensor([[1],[1],[1],[1],[1],[1],[1],[1],[1]])

In [4]:
w1 = torch.zeros(1, requires_grad = True)
b1 = torch.zeros(1, requires_grad = True)

In [5]:
hypothesis = x_train * w1 + b1
print(hypothesis)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], grad_fn=<AddBackward0>)


In [6]:
optimizer = optim.SGD([w1,b1], lr = 0.01)

nb_epochs = 1999
for epoch in range(nb_epochs + 1):
    
    hypothesis = x_train * w1 + b1
        
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    optimizer.zero_grad() # 미분값을 계속 0으로 초기화
    cost.backward() # 구한 loss로부터 back propagation을 통해 각 변수마다 loss에 대한 gradient 구해주기
                    # starting backpropagation
    optimizer.step() # starting gradient descent

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
        epoch, nb_epochs, w1.item(), b1.item(), cost.item()
        ))

Epoch    0/1999 w: 0.067, b: 0.020 Cost: 1.000000
Epoch  100/1999 w: 0.133, b: 0.417 Cost: 0.087185
Epoch  200/1999 w: 0.082, b: 0.641 Cost: 0.033114
Epoch  300/1999 w: 0.050, b: 0.779 Cost: 0.012577
Epoch  400/1999 w: 0.031, b: 0.864 Cost: 0.004777
Epoch  500/1999 w: 0.019, b: 0.916 Cost: 0.001814
Epoch  600/1999 w: 0.012, b: 0.948 Cost: 0.000689
Epoch  700/1999 w: 0.007, b: 0.968 Cost: 0.000262
Epoch  800/1999 w: 0.004, b: 0.980 Cost: 0.000099
Epoch  900/1999 w: 0.003, b: 0.988 Cost: 0.000038
Epoch 1000/1999 w: 0.002, b: 0.993 Cost: 0.000014
Epoch 1100/1999 w: 0.001, b: 0.995 Cost: 0.000005
Epoch 1200/1999 w: 0.001, b: 0.997 Cost: 0.000002
Epoch 1300/1999 w: 0.000, b: 0.998 Cost: 0.000001
Epoch 1400/1999 w: 0.000, b: 0.999 Cost: 0.000000
Epoch 1500/1999 w: 0.000, b: 0.999 Cost: 0.000000
Epoch 1600/1999 w: 0.000, b: 1.000 Cost: 0.000000
Epoch 1700/1999 w: 0.000, b: 1.000 Cost: 0.000000
Epoch 1800/1999 w: 0.000, b: 1.000 Cost: 0.000000
Epoch 1900/1999 w: 0.000, b: 1.000 Cost: 0.000000


In [7]:
w2 = torch.zeros((3,1), requires_grad = True)
b2 = torch.zeros(1, requires_grad = True)

In [8]:
optimizer = optim.SGD([w2,b2], lr = 0.01)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    
    hypothesis = x_train.matmul(w2) + b2
        
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    optimizer.zero_grad() # 미분값을 계속 0으로 초기화
    cost.backward() # 구한 loss로부터 back propagation을 통해 각 변수마다 loss에 대한 gradient 구해주기 (starting backpropagation)
    optimizer.step() # starting gradient descent

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
    epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.]) Cost: 1.000000
Epoch    1/20 hypothesis: tensor([0.3800, 0.4800, 0.5800, 0.6800, 0.7800, 0.8800, 0.9800, 1.0800, 1.1800]) Cost: 0.115067
Epoch    2/20 hypothesis: tensor([0.4503, 0.5589, 0.6676, 0.7763, 0.8849, 0.9936, 1.1023, 1.2109, 1.3196]) Cost: 0.091963
Epoch    3/20 hypothesis: tensor([0.4795, 0.5852, 0.6909, 0.7966, 0.9022, 1.0079, 1.1136, 1.2193, 1.3250]) Cost: 0.084018
Epoch    4/20 hypothesis: tensor([0.5026, 0.6039, 0.7053, 0.8067, 0.9080, 1.0094, 1.1108, 1.2121, 1.3135]) Cost: 0.076962
Epoch    5/20 hypothesis: tensor([0.5240, 0.6210, 0.7181, 0.8151, 0.9122, 1.0092, 1.1063, 1.2033, 1.3004]) Cost: 0.070502
Epoch    6/20 hypothesis: tensor([0.5444, 0.6373, 0.7302, 0.8231, 0.9160, 1.0089, 1.1018, 1.1947, 1.2875]) Cost: 0.064584
Epoch    7/20 hypothesis: tensor([0.5640, 0.6529, 0.7418, 0.8307, 0.9196, 1.0085, 1.0974, 1.1863, 1.2752]) Cost: 0.059162
Epoch    8/20 hypothesis: tensor([0.5827, 0.6678, 0.7529, 0.

# nn.Modeule로 구현하는 선형 회귀 

In [9]:
model = nn.Linear(3, 3) #input_dim = 1, output_dim = 1

# nn.Linear(input_size, output_size, bias)
- 수동으로 self.weights 와 self.bias 를 정의하고 초기화하고 xb @ self.weights + self.bias를 계산하는 대신에 이것들을 해내는 PyTorch 클래스인 nn.Linear를 선형 계층으로 사용하겠습니다.

In [10]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119],
        [ 0.2710, -0.5435,  0.3462],
        [-0.1188,  0.2937,  0.0803]], requires_grad=True), Parameter containing:
tensor([-0.0707,  0.1601,  0.0285], requires_grad=True)]


In [11]:
optimizer3 = torch.optim.SGD(model.parameters(), lr = 0.01)

In [12]:
nb_epochs = 33
for epoch in range(nb_epochs + 1):
    
    prediction = model(x_train) # x_train. shape = 9x3
    
    cost = F.mse_loss(prediction, y_train) # 평균 제곱 오차 함수
    
    optimizer3.zero_grad()
    cost.backward()
    optimizer3.step()
    

    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
    epoch, nb_epochs, cost.item()
        ))

Epoch    0/33 Cost: 0.706220
Epoch    1/33 Cost: 0.513206
Epoch    2/33 Cost: 0.411482
Epoch    3/33 Cost: 0.355884
Epoch    4/33 Cost: 0.323651
Epoch    5/33 Cost: 0.303312
Epoch    6/33 Cost: 0.289083
Epoch    7/33 Cost: 0.278045
Epoch    8/33 Cost: 0.268725
Epoch    9/33 Cost: 0.260377
Epoch   10/33 Cost: 0.252623
Epoch   11/33 Cost: 0.245269
Epoch   12/33 Cost: 0.238214
Epoch   13/33 Cost: 0.231405
Epoch   14/33 Cost: 0.224812
Epoch   15/33 Cost: 0.218418
Epoch   16/33 Cost: 0.212212
Epoch   17/33 Cost: 0.206184
Epoch   18/33 Cost: 0.200329
Epoch   19/33 Cost: 0.194642
Epoch   20/33 Cost: 0.189116
Epoch   21/33 Cost: 0.183747
Epoch   22/33 Cost: 0.178530
Epoch   23/33 Cost: 0.173462
Epoch   24/33 Cost: 0.168537
Epoch   25/33 Cost: 0.163753
Epoch   26/33 Cost: 0.159104
Epoch   27/33 Cost: 0.154587
Epoch   28/33 Cost: 0.150199
Epoch   29/33 Cost: 0.145935
Epoch   30/33 Cost: 0.141792
Epoch   31/33 Cost: 0.137766
Epoch   32/33 Cost: 0.133855
Epoch   33/33 Cost: 0.130055


C:\Users\syjy0\anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Using a target size (torch.Size([9, 1])) that is different to the input size (torch.Size([9, 3])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  


# 모델을 클래스로 구현하기

In [13]:
x_train2 = torch.FloatTensor([[1], [2], [3]])
y_train2 = torch.FloatTensor([[2], [4], [6]])

- 단순한 선형 회귀 모델

In [14]:
model2 = nn.Linear(3,2)

In [21]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1)
        
    def forward(self, x):
        return self.linear(x)

In [22]:
model4 = LinearRegressionModel()

In [23]:
optimizer2 = torch.optim.SGD(model4.parameters(), lr = 0.01)
nb_epochs = 21
for epoch in range(nb_epochs + 1):
    
    prediction = model4(x_train2)
    cost = F.mse_loss(prediction, y_train2)
    
    optimizer2.zero_grad()
    cost.backward()
    optimizer2.step()
    
    print('Epoch {:4d}/{} Cost: {:6f}'.format(
    epoch, nb_epochs, cost.item()))

Epoch    0/21 Cost: 34.374695
Epoch    1/21 Cost: 27.248152
Epoch    2/21 Cost: 21.614624
Epoch    3/21 Cost: 17.161257
Epoch    4/21 Cost: 13.640744
Epoch    5/21 Cost: 10.857602
Epoch    6/21 Cost: 8.657315
Epoch    7/21 Cost: 6.917747
Epoch    8/21 Cost: 5.542353
Epoch    9/21 Cost: 4.454821
Epoch   10/21 Cost: 3.594830
Epoch   11/21 Cost: 2.914701
Epoch   12/21 Cost: 2.376743
Epoch   13/21 Cost: 1.951166
Epoch   14/21 Cost: 1.614423
Epoch   15/21 Cost: 1.347898
Epoch   16/21 Cost: 1.136881
Epoch   17/21 Cost: 0.969739
Epoch   18/21 Cost: 0.837281
Epoch   19/21 Cost: 0.732241
Epoch   20/21 Cost: 0.648874
Epoch   21/21 Cost: 0.582641


- 다중 선형 회귀 모델

In [ ]:
model5 = nn.Linear(3,1)

In [31]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)
    def forward(self, x):
        return self.linear(x)

In [32]:
model6 = MultivariateLinearRegressionModel()

In [34]:
optimizer4 = torch.optim.SGD(model6.parameters(), lr = 0.01)
nb_epochs = 21
for epoch in range(nb_epochs + 1):
    
    prediction = model6(x_train)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer4.zero_grad()
    cost.backward()
    optimizer4.step()
    
    print('Epoch {:4d}/{} Cost: {:6f}'.format(
    epoch, nb_epochs, cost.item()))

Epoch    0/21 Cost: 10.285702
Epoch    1/21 Cost: 0.307052
Epoch    2/21 Cost: 0.128279
Epoch    3/21 Cost: 0.114943
Epoch    4/21 Cost: 0.105251
Epoch    5/21 Cost: 0.096416
Epoch    6/21 Cost: 0.088323
Epoch    7/21 Cost: 0.080909
Epoch    8/21 Cost: 0.074117
Epoch    9/21 Cost: 0.067896
Epoch   10/21 Cost: 0.062197
Epoch   11/21 Cost: 0.056976
Epoch   12/21 Cost: 0.052193
Epoch   13/21 Cost: 0.047812
Epoch   14/21 Cost: 0.043799
Epoch   15/21 Cost: 0.040122
Epoch   16/21 Cost: 0.036754
Epoch   17/21 Cost: 0.033669
Epoch   18/21 Cost: 0.030843
Epoch   19/21 Cost: 0.028254
Epoch   20/21 Cost: 0.025882
Epoch   21/21 Cost: 0.023710


# 미니배치와 배치 크기

- 데이터로드: Dataset을 커스텀하여 만들 수도 있지만 여기서는 텐서를 입력받아 Dataset의 형태로 변환해주는 TensorDataset을 사용

In [35]:
from torch.utils.data import TensorDataset # 텐서데이터셋 => 기본적으로 텐서를 입력 받는다. 텐서 형태로 데이터를 정의
from torch.utils.data import DataLoader # 데이터로드

In [38]:
dataset = TensorDataset(x_train, y_train)
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [44]:
model7 = nn.Linear(3,1)
optimizer5 = torch.optim.SGD(model7.parameters(), lr = 1e-5)

In [51]:
np_epochs = 20
for epoch in range(nb_epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        #print(batch_idx)
        #print(samples)
    #print('=' * 33)
        x_train, y_train = samples
        prediction = model7(x_train)
        cost = F.mse_loss(prediction, y_train)
        
        optimizer5.zero_grad()
        cost.backward()
        optimizer5.step()
        
        print('Epoch {:4d}/{} Batch {}/{} Cost: {:6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader), cost.item()))
    print('='*49)

Epoch    0/21 Batch 1/5 Cost: 1.947129
Epoch    0/21 Batch 2/5 Cost: 8.984169
Epoch    0/21 Batch 3/5 Cost: 5.974807
Epoch    0/21 Batch 4/5 Cost: 8.436694
Epoch    0/21 Batch 5/5 Cost: 7.347460
Epoch    1/21 Batch 1/5 Cost: 3.850255
Epoch    1/21 Batch 2/5 Cost: 1.571764
Epoch    1/21 Batch 3/5 Cost: 6.625402
Epoch    1/21 Batch 4/5 Cost: 8.882811
Epoch    1/21 Batch 5/5 Cost: 15.667125
Epoch    2/21 Batch 1/5 Cost: 11.083865
Epoch    2/21 Batch 2/5 Cost: 2.762223
Epoch    2/21 Batch 3/5 Cost: 11.393532
Epoch    2/21 Batch 4/5 Cost: 2.227818
Epoch    2/21 Batch 5/5 Cost: 2.051529
Epoch    3/21 Batch 1/5 Cost: 10.313185
Epoch    3/21 Batch 2/5 Cost: 4.612836
Epoch    3/21 Batch 3/5 Cost: 6.490991
Epoch    3/21 Batch 4/5 Cost: 0.686643
Epoch    3/21 Batch 5/5 Cost: 12.306970
Epoch    4/21 Batch 1/5 Cost: 9.701584
Epoch    4/21 Batch 2/5 Cost: 1.861492
Epoch    4/21 Batch 3/5 Cost: 8.159747
Epoch    4/21 Batch 4/5 Cost: 3.535717
Epoch    4/21 Batch 5/5 Cost: 9.468681
Epoch    5/21 Batch 

# 커스텀 데이터셋

In [52]:
'''
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self):
    # 데이터셋의 전처리를 해주는 부분    
    def __len__(self):
    # 데이터셋의 길이. 즉, 총 샘플의 수를 적어주는 부분
    def __getitem(self, idx):
    # 데이터셋에서 특정 1개의 샘플을 가져오는 함수'''

'\nclass CustomDataset(torch.utils.data.Dataset):\n    def __init__(self):\n    # 데이터셋의 전처리를 해주는 부분    \n    def __len__(self):\n    # 데이터셋의 길이. 즉, 총 샘플의 수를 적어주는 부분\n    def __getitem(self, idx):\n    # 데이터셋에서 특정 1개의 샘플을 가져오는 함수'

In [ ]:
class CustomDataset(Dataset):
    def __init__(self):
        
        self.x_data = [[1,2,3],
                       [2,2,3],
                       [3,2,3],
                       [4,2,3]]
        self.y_data = [[1],[2],[3],[4]]
        
        # 총 데이터의 개수 리턴
    def __len__(self):
        return len(self.x_data)
    
    def __getitem(self, idx):
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        
        return x, y

In [ ]:
model8 = torch.nn.Linear(3,1)
optimizer10 = torch.optim.SGD(model8.parameters(), lr = 1e-5)