In [17]:
''' 
 Author: Yoonhyuck WOO / JBNU_Industrial Information system Engineering
 Date; 7. 21. 2021 - 7. 22. 2021
 Title: Linear Regression
 Reference: https://wikidocs.net/57810'''

' \n Author: Yoonhyuck WOO / JBNU_Industrial Information system Engineering\n Date; 7. 21. 2021 - 7. 22. 2021\n Title: Linear Regression\n Reference: https://wikidocs.net/57810'

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# W값: 그래프의 경사도를 결정 (W값이 커지면 경사가 커지고, W값이 작아지면 경사가 작아집니다)
# b값: b의 값에 따라서 그래프가 좌,우로 이동하는 것을 보여준다
# 시그모이드 함수를 이용한 분류
- 시그모이드 함수의 출력값은 0과 1사이의 값을 가짐
- 임계값을 0.5라고 정함. 출력값이 0.5 이상이면 1(True), 0.5이하면 0(False)으로 판단
- 확률이라고 생각하면 해당 레이블에 속할 확률이 50%가 넘으면 해당 레이블로 판단하고, 해당 레이블에 속할 확률이 50%보다 낮으면 아니라고 판단

# 오차함수: 로지스틱회귀에서는 오차함수를 MSE로 사용하면 안된다
- 이유: 오차함수를 미분하면 비볼록(non-convex) 형태의 그래프가 나온다.
- 문제점: 경사 하강법이 오차가 최소값이 되는 구간에 도착했다고 판단한 그 구간이 실제 오차가 완전히 최소값이 되는 구간이 아닐 수 있다는 점

In [3]:
x_data = [[1,2],[2,2],[3,2],[4,2],[5,2],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [4]:
w = torch.zeros((2,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

# 예측 전 w,b

In [5]:
print(w)
print(b)

tensor([[0.],
        [0.]], requires_grad=True)
tensor([0.], requires_grad=True)


In [6]:
optimizer = optim.SGD([w,b], lr = 1)

nb_epochs = 13
for epoch in range(nb_epochs + 1):
    
    hypothesis = torch.sigmoid(x_train.matmul(w) + b)
    cost = -(y_train * torch.log(hypothesis) +
            (1 - y_train) * torch.log(1 - hypothesis)).mean()
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
    epoch, nb_epochs, cost.item()
    ))

Epoch    0/13 Cost: 0.693147
Epoch    1/13 Cost: 0.878562
Epoch    2/13 Cost: 1.156449
Epoch    3/13 Cost: 2.088164
Epoch    4/13 Cost: 0.375788
Epoch    5/13 Cost: 0.422735
Epoch    6/13 Cost: 0.712797
Epoch    7/13 Cost: 0.306652
Epoch    8/13 Cost: 0.395427
Epoch    9/13 Cost: 0.267403
Epoch   10/13 Cost: 0.306452
Epoch   11/13 Cost: 0.223569
Epoch   12/13 Cost: 0.228967
Epoch   13/13 Cost: 0.192086


In [7]:
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)

tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])


# 예측 후 w,b

In [8]:
print(w)
print(b)

tensor([[ 1.6804],
        [-2.0070]], requires_grad=True)
tensor([-1.0035], requires_grad=True)


# nn.Modeul (nn.Sigmoid 사용)

In [9]:
x_data1 = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
x_train1 = torch.FloatTensor(x_data1)

In [10]:
model = nn.Sequential(
nn.Linear(2,1),
nn.Sigmoid())

In [11]:
model(x_train1)

tensor([[0.5386],
        [0.5754],
        [0.3204],
        [0.4499],
        [0.3885],
        [0.2483]], grad_fn=<SigmoidBackward>)

In [12]:
optimizer1 = optim.SGD(model.parameters(), lr = 1)
nb_epochs = 100
for epoch in range(nb_epochs + 1):
    hypothesis = model(x_train1)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer1.zero_grad()
    cost.backward()
    optimizer1.step()
    
    prediction = hypothesis >= torch.FloatTensor([0.5])
    correct_prediction = prediction.float() == y_train
    accuracy = correct_prediction.sum().item() / len(correct_prediction)
    
    print('Epoch {:4d}/{} Cost: {:6f} Accuracy {:2.2f}%'.format(
    epoch, nb_epochs, cost.item(), accuracy * 100,
    ))

Epoch    0/100 Cost: 0.858931 Accuracy 16.67%
Epoch    1/100 Cost: 1.520122 Accuracy 50.00%
Epoch    2/100 Cost: 0.961638 Accuracy 50.00%
Epoch    3/100 Cost: 2.201398 Accuracy 50.00%
Epoch    4/100 Cost: 0.449557 Accuracy 83.33%
Epoch    5/100 Cost: 0.550127 Accuracy 66.67%
Epoch    6/100 Cost: 1.043686 Accuracy 50.00%
Epoch    7/100 Cost: 0.659785 Accuracy 66.67%
Epoch    8/100 Cost: 1.281957 Accuracy 50.00%
Epoch    9/100 Cost: 0.432780 Accuracy 66.67%
Epoch   10/100 Cost: 0.544474 Accuracy 83.33%
Epoch   11/100 Cost: 0.530235 Accuracy 66.67%
Epoch   12/100 Cost: 0.833761 Accuracy 66.67%
Epoch   13/100 Cost: 0.469911 Accuracy 66.67%
Epoch   14/100 Cost: 0.651454 Accuracy 66.67%
Epoch   15/100 Cost: 0.457928 Accuracy 83.33%
Epoch   16/100 Cost: 0.624492 Accuracy 66.67%
Epoch   17/100 Cost: 0.434564 Accuracy 83.33%
Epoch   18/100 Cost: 0.573685 Accuracy 83.33%
Epoch   19/100 Cost: 0.417370 Accuracy 83.33%
Epoch   20/100 Cost: 0.542982 Accuracy 83.33%
Epoch   21/100 Cost: 0.402111 Accu

# 클래스로 모델 구현하기

In [13]:
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,x):
        return self.sigmoid(self.linear(x))

In [14]:
torch.manual_seed(1)

In [15]:
model1 = BinaryClassifier()

In [16]:
optimizer2 = optim.SGD(model1.parameters(), lr = 1)
nb_epochs = 33
for epoch in range(nb_epochs + 1):
    hypothesis = model1(x_train)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    

    optimizer2.zero_grad()
    cost.backward()
    optimizer2.step()
    
    prediction = hypothesis >= torch.FloatTensor([0.5])
    correct_prediction = prediction.float() == y_train
    accuracy = correct_prediction.sum().item() / len(correct_prediction)
    print('Epoch {:4d}/{} Cost:{:.6f} Accuracy {:2.2f}%'.format(
    epoch, nb_epochs, cost.item(), accuracy * 100))

Epoch    0/33 Cost:0.496892 Accuracy 83.33%
Epoch    1/33 Cost:0.427390 Accuracy 83.33%
Epoch    2/33 Cost:0.383873 Accuracy 83.33%
Epoch    3/33 Cost:0.377769 Accuracy 100.00%
Epoch    4/33 Cost:0.483589 Accuracy 66.67%
Epoch    5/33 Cost:0.527673 Accuracy 66.67%
Epoch    6/33 Cost:0.993595 Accuracy 66.67%
Epoch    7/33 Cost:0.245949 Accuracy 100.00%
Epoch    8/33 Cost:0.259831 Accuracy 83.33%
Epoch    9/33 Cost:0.242809 Accuracy 100.00%
Epoch   10/33 Cost:0.261455 Accuracy 83.33%
Epoch   11/33 Cost:0.222988 Accuracy 100.00%
Epoch   12/33 Cost:0.228899 Accuracy 83.33%
Epoch   13/33 Cost:0.197163 Accuracy 100.00%
Epoch   14/33 Cost:0.193258 Accuracy 83.33%
Epoch   15/33 Cost:0.176282 Accuracy 100.00%
Epoch   16/33 Cost:0.170355 Accuracy 100.00%
Epoch   17/33 Cost:0.162177 Accuracy 100.00%
Epoch   18/33 Cost:0.157485 Accuracy 100.00%
Epoch   19/33 Cost:0.153080 Accuracy 100.00%
Epoch   20/33 Cost:0.149689 Accuracy 100.00%
Epoch   21/33 Cost:0.146662 Accuracy 100.00%
Epoch   22/33 Cost:0