In [35]:
import torch
import numpy as np
import time
tensor = torch.ones(4,4)

print('First row', tensor[0])
print('First column', tensor[:, 2])
print('Last column', tensor[..., -1])
tensor[:,1] = 3
print(tensor)


First row tensor([1., 1., 1., 1.])
First column tensor([1., 1., 1., 1.])
Last column tensor([1., 1., 1., 1.])
tensor([[1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.]])


In [3]:
w = torch.tensor(2.0, requires_grad = True)
y = w ** 2
z = 2*y + 5
print(w)

tensor(2., requires_grad=True)


In [3]:
a = z.backward() # 그냥 수식을 w에 대해 미분

print('a:',a)

print('수식을 w로 미분한 값: {}'.format(w.grad)) # 미분후 w에 2값(앞에서 설정해 준) 대입

a: None
수식을 w로 미분한 값: 8.0


In [5]:
sample = set('you need to run'.split())

In [7]:
print(sample)

{'run', 'you', 'need', 'to'}


In [14]:
sample1 = 'you need to run'.count('u')

In [15]:
print(sample1)

2


In [8]:
import copy
q = [1,2,3,4]
c = copy.deepcopy(q)
c[0] = 13
print(q)
print(c)

[1, 2, 3, 4]
[13, 2, 3, 4]


In [20]:
a = [[1,2,3,4],
     [5,6,7,8]]
a = np.array(a)
# b = copy.deepcopy(a)
# b[0] = 13
# print(a)
# print(b)

In [24]:
print(a[:, :-1])
print(a[:, 1:])

[[1 2 3]
 [5 6 7]]
[[2 3 4]
 [6 7 8]]


In [27]:
start = time.time()
elapsed = time.time() - start

print(start)
print(elapsed)

1633447184.99242
0.0


In [33]:
k = torch.zeros(3,1,7)
print(k)

tensor([[[0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.]]])


In [49]:
import torchtext
from torchtext.datasets import WikiText2
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

In [65]:
sent = "I want to be a Ji sung Park"
a = get_tokenizer("basic_english")
token = a("I want to be a Ji sung Park")
print(token)

['i', 'want', 'to', 'be', 'a', 'ji', 'sung', 'park']


In [66]:
vocab = build_vocab_from_iterator(token,specials=["<unk>"])
print(vocab)

Vocab()


In [68]:
vocab = build_vocab_from_iterator(map(token, {1:'a',2:'b',3:'c'}), specials=['<unk>']) 
vocab.set_default_index(vocab['<unk>'])


TypeError: 'list' object is not callable

In [54]:
a = ['1', '1', '1', '3', '3']
a['1']

TypeError: list indices must be integers or slices, not str

In [55]:
a = "I AM"

In [56]:
print(a)

I AM


In [91]:
import io
from torchtext.vocab import build_vocab_from_iterator
def yield_tokens(file_path):
    with io.open(file_path, encoding = 'utf-8') as f:
        for line in f:
            yield line.strip().split()
            print(line)
vocab = build_vocab_from_iterator(yield_tokens(r"C:\Users\LG\Desktop\JBNU_ISE\GITHUB\JBNU-2021-Summer\Pytorch tutorial\Text\textfile.txt"), specials=["<unk>"])

I

want

to

be

Ji

Sung

Park


In [97]:
vocab(['I','want','to','be','Ji','Sung','Park'])

[1, 7, 6, 5, 2, 4, 3]

In [103]:
text_pipeline = lambda x: vocab(get_tokenizer(x))
label_pipeline = lambda x: int(x) - 1
text_pipeline("I want to be Ji Sung Park")

ValueError: Requested tokenizer I want to be Ji Sung Park, valid choices are a callable that takes a single string as input, "revtok" for the revtok reversible tokenizer, "subword" for the revtok caps-aware tokenizer, "spacy" for the SpaCy English tokenizer, or "moses" for the NLTK port of the Moses tokenization script.

In [93]:
j = yield_tokens(r"C:\Users\LG\Desktop\JBNU_ISE\GITHUB\JBNU-2021-Summer\Pytorch tutorial\Text\textfile.txt")
print(j)

<generator object yield_tokens at 0x000001D46FD05430>


In [94]:
from torchtext.datasets import AG_NEWS
train_iter2 = AG_NEWS(split = 'train')

C:\Users\LG\Desktop\JBNU_ISE\GITHUB\JBNU-2021-Summer\Pytorch tutorial\.data\AG_NEWS\train.csv: 29.5MB [00:02, 13.8MB/s]


In [95]:
next(train_iter2)

(3,
 "Wall St. Bears Claw Back Into the Black (Reuters) Reuters - Short-sellers, Wall Street's dwindling\\band of ultra-cynics, are seeing green again.")

In [104]:
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

tokenizer = get_tokenizer('basic_english')
train_iter = AG_NEWS(split='train')

def yield_tokens(data_iter):
    for _, text in data_iter:
        yield tokenizer(text)

vocab = build_vocab_from_iterator(yield_tokens(train_iter), specials=["<unk>"])
vocab.set_default_index(vocab["<unk>"])

In [114]:
text_pipeline = lambda x: vocab(tokenizer(x))
label_pipeline = lambda x: int(x) - 1
#text_pipeline("I")
label_pipeline('')

ValueError: invalid literal for int() with base 10: '10.5'

In [145]:
g = torch.randn(1,2,3)
print(g)
print(torch.numel(g))

tensor([[[ 0.9012,  1.6884, -0.7175],
         [ 2.4750, -0.0362, -0.0494]]])
6


In [148]:
o = filter(lambda t: t.numel() > 0, g)
p = tuple(o)
print(p)

(tensor([[ 0.9012,  1.6884, -0.7175],
        [ 2.4750, -0.0362, -0.0494]]),)


In [147]:
q = torch.cat(p)
print(q)

tensor([[ 0.9012,  1.6884, -0.7175],
        [ 2.4750, -0.0362, -0.0494]])
