In [2]:
import torch
import numpy as np
import time
tensor = torch.ones(4,4)

print('First row', tensor[0])
print('First column', tensor[:, 2])
print('Last column', tensor[..., -1])
tensor[:,1] = 3
print(tensor)


First row tensor([1., 1., 1., 1.])
First column tensor([1., 1., 1., 1.])
Last column tensor([1., 1., 1., 1.])
tensor([[1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.]])


In [45]:
rnn = RNN(n_letters, 128, n_letters)

n_iters = 100000
print_every = 5000
plot_every = 500
all_losses = []
total_loss = 0 # Reset every plot_every iters

start = time.time()

for iter in range(1, n_iters + 1):
    output, loss = train(*randomTrainingExample())
    total_loss += loss

    if iter % print_every == 0:
        print('%s (%d %d%%) %.4f' % (timeSince(start), iter, iter / n_iters * 100, loss))

    if iter % plot_every == 0:
        all_losses.append(total_loss / plot_every)
        total_loss = 0

ValueError: Expected input batch_size (1) to match target batch_size (0).

In [3]:
w = torch.tensor(2.0, requires_grad = True)
y = w ** 2
z = 2*y + 5
print(w)

tensor(2., requires_grad=True)


In [4]:
a = z.backward() # 그냥 수식을 w에 대해 미분

print('a:',a)

print('수식을 w로 미분한 값: {}'.format(w.grad)) # 미분후 w에 2값(앞에서 설정해 준) 대입

a: None
수식을 w로 미분한 값: 8.0


In [5]:
sample = set('you need to run'.split())

In [6]:
print(sample)

{'to', 'you', 'run', 'need'}


In [7]:
sample1 = 'you need to run'.count('u')

In [8]:
print(sample1)

2


In [9]:
import copy
q = [1,2,3,4]
c = copy.deepcopy(q)
c[0] = 13
print(q)
print(c)

[1, 2, 3, 4]
[13, 2, 3, 4]


In [10]:
a = [[1,2,3,4],
     [5,6,7,8]]
a = np.array(a)
# b = copy.deepcopy(a)
# b[0] = 13
# print(a)
# print(b)

In [11]:
print(a[:, :-1])
print(a[:, 1:])

[[1 2 3]
 [5 6 7]]
[[2 3 4]
 [6 7 8]]


In [12]:
start = time.time()
elapsed = time.time() - start

print(start)
print(elapsed)

1633787019.6264668
0.0


In [13]:
k = torch.zeros(3,1,7)
print(k)

tensor([[[0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.]]])


In [14]:
import torchtext
from torchtext.datasets import WikiText2
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

In [15]:
sent = "I want to be a Ji sung Park"
a = get_tokenizer("basic_english")
token = a("I want to be a Ji sung Park")
print(token)

['i', 'want', 'to', 'be', 'a', 'ji', 'sung', 'park']


In [16]:
vocab = build_vocab_from_iterator(token,specials=["<unk>"])
print(vocab)

Vocab()


In [ ]:
vocab = build_vocab_from_iterator(map(token, {1:'a',2:'b',3:'c'}), specials=['<unk>']) 
vocab.set_default_index(vocab['<unk>'])


In [ ]:
a = ['1', '1', '1', '3', '3']
a['1']

In [ ]:
a = "I AM"

In [ ]:
print(a)

In [ ]:
import io
from torchtext.vocab import build_vocab_from_iterator
def yield_tokens(file_path):
    with io.open(file_path, encoding = 'utf-8') as f:
        for line in f:
            yield line.strip().split()
            print(line)
vocab = build_vocab_from_iterator(yield_tokens(r"C:\Users\LG\Desktop\JBNU_ISE\GITHUB\JBNU-2021-Summer\Pytorch tutorial\Text\textfile.txt"), specials=["<unk>"])

In [ ]:
vocab(['I','want','to','be','Ji','Sung','Park'])

In [ ]:
text_pipeline = lambda x: vocab(get_tokenizer(x))
label_pipeline = lambda x: int(x) - 1
text_pipeline("I want to be Ji Sung Park")

In [ ]:
j = yield_tokens(r"C:\Users\LG\Desktop\JBNU_ISE\GITHUB\JBNU-2021-Summer\Pytorch tutorial\Text\textfile.txt")
print(j)

In [ ]:
from torchtext.datasets import AG_NEWS
train_iter2 = AG_NEWS(split = 'train')

In [ ]:
next(train_iter2)

In [ ]:
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

tokenizer = get_tokenizer('basic_english')
train_iter = AG_NEWS(split='train')

def yield_tokens(data_iter):
    for _, text in data_iter:
        yield tokenizer(text)

vocab = build_vocab_from_iterator(yield_tokens(train_iter), specials=["<unk>"])
vocab.set_default_index(vocab["<unk>"])

In [ ]:
text_pipeline = lambda x: vocab(tokenizer(x))
label_pipeline = lambda x: int(x) - 1
#text_pipeline("I")
label_pipeline('')

In [ ]:
g = torch.randn(10,2,3)
print(g)
#print(torch.numel(g))

In [ ]:
print(g.size(0))
bsz = 5
seq_len = g.size(0) // bsz
print('seq_len:',seq_len)
#print(seq_len)
g = g[:seq_len * bsz]
#print(data)
g = g.view(bsz, seq_len).t()#.contiguous()
print(g)
print(g.t())

In [ ]:
v = torch.randn(10,2,3)
print(v)
# print('='*58)
# print(v[:3])
# print('='*58)


# print('-'*33)
# data1 = data.view(bsz, seq_len)
# print(data1)

# print('='*58)
# data2 = data1.view(-1, seq_len).t()
# print(data1)

# print('='*58)
# data1 = data.view(-1, seq_len).t().contiguous()
# print(data1)
# # v = v
# # o = filter(lambda t: t.numel() > 0, v)
# # p = tuple(o)

# # print(p)

In [18]:
q = torch.cat(p)
print(q)

NameError: name 'p' is not defined

In [19]:
  for batch, i in enumerate(range(0, 22 - 1, 3)):
        print('batch: ', batch, 'i: ',i)

batch:  0 i:  0
batch:  1 i:  3
batch:  2 i:  6
batch:  3 i:  9
batch:  4 i:  12
batch:  5 i:  15
batch:  6 i:  18


In [ ]:
bptt = 35 # chunks of length
def get_batch(source, i): # -> Tuple[Tensor, Tensor]
    """
    Args:
        source: Tensor, shape [full_seq_len, batch_size]
        i: int

    Returns:
        tuple (data, target), where data has shape [seq_len, batch_size] and
        target has shape [seq_len * batch_size]
    """
    print('len(source)', len(source))
    seq_len = min(bptt, len(source) - 1 - i)
    print('seq_len', seq_len)
    
    data = source[i:i+seq_len]
    target = source[i+1:i+1+seq_len].reshape(-1)
    return data, target


get_batch(v,1)

In [ ]:
def generate_square_subsequent_mask(sz: int):#->Tensor
    """
    Generates an upper-triangular matrix of -inf, with zeros on diag.
    triu: Generates an upper-triangular matrix
    """
    return torch.triu(torch.ones(sz, sz) * float('-inf'), diagonal = 1)


generate_square_subsequent_mask(5)

In [1]:
qwer = [1,2,3,4]
xyz = [1,2,3,4]
for p in qwer:
    p.add_(xyz, alpha=-0.5)
    print(p)

AttributeError: 'int' object has no attribute 'add_'